author: JuicyDev
description: Alchemy bag plugin (based off of equivilant exchange)
main: juicydev.alcbags.AlcBags
name: AlcBags
version: '1.1'
softdepend: [JCore]
commands:
    alcbags:
        aliases: [alcbag]
        descriptions: Base alcbags command.